spring:
  application:
    name: fb-livescore
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
    web:
      pageable:
        default-page-size: 20
        one-indexed-parameters: true
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
  messages:
    basename: i18n/messages
  task:
    execution:
      thread-name-prefix: interaction-cloud-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: interaction-cloud-scheduling-
      pool:
        size: 2
  thymeleaf:
    mode: HTML
    enabled: false
  output:
    ansi:
      console-available: true
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://${IP}:3306/livescore?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    sql-script-encoding: UTF-8


IP: 127.0.0.1
logging:
  level:
    ROOT: INFO
    com.peng: DEBUG

server:
  port: 8081
  servlet:
    session:
      cookie:
        http-only: true
